BEGIN;
-- Preserve 001: databases created in phase 0 can be upgraded.
-- Locate the original autogenerated temporal CHECK rather than assume its name.
DO $$
DECLARE constraint_name text;
BEGIN
 SELECT conname INTO STRICT constraint_name FROM pg_constraint
 WHERE conrelid='parking_rules'::regclass AND contype='c'
 AND pg_get_constraintdef(oid) LIKE '%lower_inf%'
 AND pg_get_constraintdef(oid) LIKE '%upper_inf%';
 EXECUTE format('ALTER TABLE parking_rules DROP CONSTRAINT %I',constraint_name);
END $$;
ALTER TABLE parking_rules ADD CONSTRAINT parking_rules_period_check CHECK (
 NOT isempty(valid_during) AND NOT lower_inf(valid_during)
 AND isfinite(lower(valid_during)) AND lower_inc(valid_during)
 AND (upper_inf(valid_during) OR (isfinite(upper(valid_during)) AND NOT upper_inc(valid_during)))
);
COMMENT ON COLUMN parking_rules.valid_during IS 'Finite effective start; NULL upper bound means no declared end. Adapters clip to requested period, never invent a legal end date.';
INSERT INTO schema_migrations(version) VALUES (2);
COMMIT;
