import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import type {AddressInfo} from 'node:net';
import {createApi,RateLimiter} from '../apps/web/server/api.js';
import {demoDependencies} from './support/web-demo.js';
import {webServer} from '../apps/web/server/server.js';
const now=Date.parse('2026-09-07T12:00:00Z'),valid={latitude:45.76,longitude:4.832,start:new Date(now).toISOString(),end:new Date(now+14400000).toISOString(),vehicle:{vehicleType:'CAR'}};
function setup(){return {...demoDependencies(),now:()=>now};}
function post(body:unknown,headers:Record<string,string>={}){return new Request('http://localhost/api/parking/check',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});}
test('API valid coordinates -> 200 normalized ALLOWED + PAID',async()=>{const r=await createApi(setup())(post(valid),'test');assert.equal(r.status,200);const b=await r.json();assert.equal(b.decision.status,'ALLOWED');assert.equal(b.pricing.status,'PAID');assert.equal(r.headers.get('cache-control'),'no-store');});
for(const [name,changes] of [['latitude',{latitude:91}],['longitude',{longitude:181}],['string',{latitude:'45.76'}],['end<=start',{end:valid.start}],['over24h',{end:new Date(now+90000000).toISOString()}],['no timezone',{start:'2026-09-07T12:00:00'}],['invalid date',{start:'2026-02-30T12:00:00Z'}],['future',{start:'2027-01-01T12:00:00Z',end:'2027-01-01T13:00:00Z'}],['unknown field',{password:'secret'}],['weight',{vehicle:{vehicleType:'CAR',weightKg:-1}}],['energy',{vehicle:{vehicleType:'CAR',energy:'fiction'}}],['vehicle field',{vehicle:{vehicleType:'CAR',plate:'private'}}]] as const)test(`API rejects ${name}`,async()=>{const r=await createApi(setup())(post({...valid,...changes}),'test');assert.equal(r.status,400);assert.equal((await r.json()).error.code,'INVALID_INPUT');});
test('API invalid JSON -> structured 400',async()=>{const r=await createApi(setup())(new Request('http://localhost/api/parking/check',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'}),'test');assert.equal(r.status,400);});
test('API content type and payload limit',async()=>{const api=createApi(setup());assert.equal((await api(post(valid,{'Content-Type':'text/plain'}),'t')).status,415);assert.equal((await api(post({large:'x'.repeat(9000)}),'t')).status,413);});
test('Outside Lyon -> controlled 422, no fabricated coverage',async()=>{const r=await createApi(setup())(post({...valid,longitude:2.35,latitude:48.85}),'t');assert.equal(r.status,422);assert.equal((await r.json()).error.code,'OUTSIDE_CITY');});
test('Business UNKNOWN -> 200 with alternatives',async()=>{const r=await createApi(setup())(post({...valid,longitude:4.833}),'t');assert.equal(r.status,200);const b=await r.json();assert.equal(b.decision.status,'UNKNOWN');assert.equal(b.nearbyParkings.length,3);});
test('Unavailable business service -> sanitized 503',async()=>{const d=setup();d.check=async()=>{throw new Error('postgres://private:secret@db/address');};const r=await createApi(d)(post(valid),'t');assert.equal(r.status,503);assert.ok(!(await r.text()).includes('secret'));});
test('Application operational failure is not reported as business UNKNOWN',async()=>{const d=setup(),base=await d.check(valid as Parameters<typeof d.check>[0],new Date(now).toISOString());d.check=async()=>({...base,failure:'SERVICE_UNAVAILABLE'});assert.equal((await createApi(d)(post(valid),'t')).status,503);});
test('FORBIDDEN remains forbidden with PAID and three facilities',async()=>{const r=await createApi(setup())(post({...valid,longitude:4.83}),'t');const b=await r.json();assert.equal(b.decision.status,'FORBIDDEN');assert.equal(b.pricing.status,'PAID');assert.equal(b.nearbyParkings.length,3);});
test('Future restriction preserves both deadlines in API',async()=>{const r=await createApi(setup())(post({...valid,longitude:4.831}),'t');const b=await r.json();assert.equal(b.decision.status,'CONDITIONAL');assert.equal(b.allowedUntil,'2026-09-07T14:00:00.000Z');assert.equal(b.mustLeaveBefore,b.allowedUntil);});
test('Rate limit and Retry-After; normal twenty checks allowed',async()=>{const api=createApi(setup());for(let i=0;i<20;i++)assert.equal((await api(post(valid),'one')).status,200);const r=await api(post(valid),'one');assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'60');assert.equal((await api(post(valid),'two')).status,200);});
test('Rate limiter expires counts',()=>{const l=new RateLimiter();assert.ok(l.take('a',1,0));assert.equal(l.take('a',1,1),false);assert.ok(l.take('a',1,60000));});
test('Same-origin API rejects cross-site and never opens wildcard CORS',async()=>{const api=createApi(setup());const r=await api(post(valid,{Origin:'https://evil.example'}),'t');assert.equal(r.status,403);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.equal((await api(post(valid,{'Sec-Fetch-Site':'cross-site'}),'t')).status,403);});
test('Autocomplete minimum length, max five and provider failure',async()=>{const d=setup(),api=createApi(d);assert.equal((await api(new Request('http://localhost/api/geocoding/autocomplete?q=ab'),'t')).status,400);const r=await api(new Request('http://localhost/api/geocoding/autocomplete?q=adresse'),'t');assert.equal((await r.json()).suggestions.length,5);d.geocoder.autocomplete=async()=>{throw new Error('private');};assert.equal((await api(new Request('http://localhost/api/geocoding/autocomplete?q=abc'),'t')).status,503);});
test('Reverse validates coordinates and preserves provider DTO',async()=>{const api=createApi(setup());assert.equal((await api(new Request('http://localhost/api/geocoding/reverse?latitude=&longitude=4'),'t')).status,400);const r=await api(new Request('http://localhost/api/geocoding/reverse?latitude=45.76&longitude=4.83'),'t');assert.equal(r.status,200);assert.equal((await r.json()).location.provider,'fixture');});
test('Health and readiness distinguish DB outage without leaking details',async()=>{const d=setup();d.ready=async()=>false;const api=createApi(d);assert.deepEqual(await (await api(new Request('http://localhost/api/health'),'t')).json(),{status:'ok'});assert.equal((await api(new Request('http://localhost/api/ready'),'t')).status,503);});
test('Logs contain event/status/timing only',async()=>{const entries:unknown[]=[];const d=setup();d.log=(...args)=>entries.push(args);await createApi(d)(post(valid),'sensitive-client');const log=JSON.stringify(entries);for(const secret of ['45.76','4.832','sensitive-client','latitude'])assert.ok(!log.includes(secret));assert.ok(log.includes('parking.check.success'));});
const http=webServer(setup(),'http://localhost');let base='';before(async()=>{await new Promise<void>(r=>http.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+(http.address() as AddressInfo).port;});after(async()=>{http.closeAllConnections();await new Promise<void>(r=>http.close(()=>r()));});
test('Real HTTP boundary returns JSON and security headers',async()=>{const r=await fetch(base+'/api/health');assert.equal(r.status,200);assert.equal(r.headers.get('x-frame-options'),'DENY');assert.match(r.headers.get('content-security-policy')??'',/frame-ancestors 'none'/);});
test('Real HTTP boundary rejects oversized body before dispatch',async()=>{const r=await fetch(base+'/api/parking/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({blob:'x'.repeat(9000)})});assert.equal(r.status,413);});
