import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseDiaLog,geometry,geometries} from '../packages/adapters/src/dialog/parser.js';
import {DiaLogHttpClient} from '../packages/adapters/src/dialog/http.js';
import {DiaLogDataSourceAdapter} from '../packages/adapters/src/dialog/adapter.js';
import {ParkingDecisionEngine,decide} from '../packages/engine/src/index.js';
import type {RuleSnapshot} from '../packages/domain/src/index.js';
const now='2026-09-05T12:00:00Z';
const query={cityId:'ci-city',zoneId:'ci-zone',start:now,end:'2026-09-05T16:00:00Z'};
async function xml(name='parking-active'){return readFile(`tests/fixtures/dialog/dialog-${name}.xml`,'utf8');}
async function parse(s:string,options:Parameters<typeof parseDiaLog>[2]={}){return parseDiaLog((async function*(){for(let i=0;i<s.length;i+=97)yield s.slice(i,i+97);})(),now,options);}
const engine=new ParkingDecisionEngine();
async function snapshot(name='parking-active',time=now){const r=await parse(await xml(name));return new DiaLogDataSourceAdapter(async()=>({rules:r.rules,retrievedAt:time})).load(query);}
test('DiaLog active -> bounded provider-independent ParkingRule -> FORBIDDEN',async()=>{const s=await snapshot();assert.equal(s.complete,false);assert.equal(s.rules[0]?.effect,'FORBIDDEN');assert.equal(s.rules[0]?.source.legalAuthority,'informative');assert.equal(engine.evaluate(query,[s],now).status,'FORBIDDEN');});
for(const [name,start,end,active] of [['future','2026-09-05T14:00:00.000Z','2026-09-05T18:00:00.000Z',true],['expired','2026-09-01T10:00:00.000Z','2026-09-02T18:00:00.000Z',false],['permanent','2026-09-05T10:00:00.000Z',null,true]] as const)test(`DiaLog ${name} normalization`,async()=>{const r=(await parse(await xml('parking-'+name))).rules[0]!;assert.equal(r.start,start);assert.equal(r.end,end);assert.equal(r.active,active);assert.equal(r.permanent,end===null);});
test('missing optional description and URL accepted without invented update time',async()=>{const r=(await parse(await xml())).rules[0]!;assert.equal(r.description,'');assert.equal(r.source.sourceUpdatedAt,undefined);assert.equal(r.source.retrievedAt,now);});
test('expired data never prohibits',async()=>assert.equal(engine.evaluate(query,[await snapshot('parking-expired')],now).status,'UNKNOWN'));
test('future restriction alone cannot invent current permission',async()=>assert.equal(engine.evaluate(query,[await snapshot('parking-future')],now).status,'UNKNOWN'));
test('B: explicit current permission plus future restriction -> CONDITIONAL allowedUntil',async()=>{const s=await snapshot('parking-future');const source={...s.coverageSource,id:'fixture-allow',adapterId:'fixture-allow',synthetic:true};delete source.legalAuthority;
 const allowed:RuleSnapshot={...query,adapterId:'fixture-allow',complete:true,coverageSource:source,rules:[{...query,id:'allow',end:'2026-09-05T14:00:00Z',effect:'ALLOWED',conditions:[],source}]};
 const d=engine.evaluate(query,[allowed,s],now);assert.equal(d.status,'CONDITIONAL');assert.equal(d.allowedUntil,'2026-09-05T14:00:00.000Z');});
test('stale restriction -> UNKNOWN',async()=>{const s=await snapshot();assert.equal(engine.evaluate(query,[s],'2026-09-07T12:00:00Z').status,'UNKNOWN');});
test('overlap retains both source rule identifiers',async()=>{const s=await snapshot('multiple');const d=engine.evaluate(query,[s],now);assert.equal(d.status,'FORBIDDEN');assert.equal(d.segments[0]?.ruleIds.length,2);});
test('unknown type ignored',async()=>{const r=await parse(await xml('unknown-restriction'));assert.equal(r.rules.length,0);assert.equal(r.stats.ignored,1);});
test('XML malformed fails',async()=>assert.rejects(()=>xml().then(s=>parse(s.slice(0,-20))),{code:'XML'}));
test('wrong DATEX version fails',async()=>assert.rejects(()=>xml().then(s=>parse(s.replace('modelBaseVersion="3"','modelBaseVersion="2"'))),{code:'SCHEMA'}));
test('XXE declaration fails',async()=>assert.rejects(()=>parse('<!DOCTYPE a [<!ENTITY e SYSTEM "file:///etc/passwd">]><a>&e;</a>'),{code:'XML'}));
test('unknown entity fails',async()=>assert.rejects(()=>xml().then(s=>parse(s.replace('ARR-FICTIF-01','&unknown;'))),{code:'XML'}));
test('size limit fails',async()=>assert.rejects(()=>xml().then(s=>parse(s,{maxBytes:20})),{code:'LIMIT'}));
test('depth limit fails',async()=>assert.rejects(()=>xml().then(s=>parse(s.replace('ARR-FICTIF-01','<a>'.repeat(70)+'x'+'</a>'.repeat(70)))),{code:'LIMIT'}));
test('recurrence preserved and explicitly unsupported',async()=>{const r=await parse(await xml('recurrence'));assert.equal(r.rules[0]?.supported,false);assert.ok(r.rules[0]?.recurrence.length);assert.equal((await decide(query,[new DiaLogDataSourceAdapter(async()=>({rules:r.rules,retrievedAt:now}))],now)).status,'UNKNOWN');});
test('stable identity across downloads and end-date updates',async()=>{const s=await xml();const a=await parse(s);const b=await parse(s.replaceAll('18:00:00','19:00:00'));assert.equal(a.rules[0]?.externalId,b.rules[0]?.externalId);assert.notEqual(a.rules[0]?.end,b.rules[0]?.end);});
test('identical duplicated orders deduplicate',async()=>{const s=await xml();const o=s.match(/<trafficRegulationOrder .*?<\/trafficRegulationOrder>/s)![0];const r=await parse(s.replace(o,o+o));assert.equal(r.rules.length,1);});
for(const g of [{type:'Point',coordinates:[4,44]},{type:'LineString',coordinates:[[4,44],[4.01,44]]},{type:'Polygon',coordinates:[[[4,44],[5,44],[5,45],[4,44]]]},{type:'MultiPolygon',coordinates:[[[[4,44],[5,44],[5,45],[4,44]]]]}])test(`geometry ${g.type} retains lon/lat`,()=>assert.deepEqual(geometry(g),g));
for(const g of [{type:'Point',coordinates:[181,44]},{type:'Point',coordinates:[4,91]},{type:'Point',coordinates:[4,44,1]},{type:'LineString',coordinates:[[4,44]]},{type:'Polygon',coordinates:[[[4,44],[5,44],[5,45],[4,45]]]}])test('invalid geometry rejected '+JSON.stringify(g),()=>assert.throws(()=>geometry(g)));
test('observed MultiLineString and GeometryCollection explicitly split',()=>assert.deepEqual(geometries({type:'GeometryCollection',geometries:[{type:'MultiLineString',coordinates:[[[4,44],[5,44]]]},{type:'MultiPoint',coordinates:[[4,44]]}]}).map(g=>g.type),['LineString','Point']));
test('HTTP streaming parse success',async()=>{const s=await xml();const r=await new DiaLogHttpClient({fetch:async()=>new Response(s)}).download(now);assert.equal(r.rules.length,1);});
test('HTTP 429 typed, Retry-After and no retry',async()=>{let n=0;await assert.rejects(()=>new DiaLogHttpClient({fetch:async()=>{n++;return new Response('',{status:429,headers:{'retry-after':'3'}});}}).download(now),{code:'RATE_LIMITED',retryAfterMs:3000});assert.equal(n,1);});
test('HTTP 503 retries once',async()=>{let n=0;const s=await xml();const r=await new DiaLogHttpClient({fetch:async()=>++n===1?new Response('',{status:503}):new Response(s)}).download(now);assert.equal(n,2);assert.equal(r.rules.length,1);});
test('HTTP 404 fails without retry',async()=>{let n=0;await assert.rejects(()=>new DiaLogHttpClient({fetch:async()=>{n++;return new Response('',{status:404});}}).download(now),{code:'HTTP'});assert.equal(n,1);});
test('HTTP timeout includes ignored abort',async()=>assert.rejects(()=>new DiaLogHttpClient({timeoutMs:10,retries:0,fetch:async()=>new Promise(()=>{})}).download(now),{code:'TIMEOUT'}));
test('malformed supplied fixture produces controlled error',async()=>assert.rejects(()=>xml('invalid').then(s=>parse(s)),e=>e instanceof Error&&e.name==='DiaLogError'));
test('one invalid order among 200 is isolated',async()=>{const s=await xml();const o=s.match(/<trafficRegulationOrder .*?<\/trafficRegulationOrder>/s)![0];const r=await parse(s.replace(o,o.repeat(199)+o.replaceAll('10:00:00','bad-date')));assert.equal(r.stats.invalid,1);assert.equal(r.rules.length,1);});
test('half invalid orders abort import',async()=>{const s=await xml();const o=s.match(/<trafficRegulationOrder .*?<\/trafficRegulationOrder>/s)![0];await assert.rejects(()=>parse(s.replace(o,o+o.replaceAll('10:00:00','bad-date'))),{code:'QUALITY'});});
test('unknown boolean structure never becomes unconditional prohibition',async()=>{const r=await parse((await xml()).replace('<operator>and</operator>','<operator>or</operator>'));assert.equal(r.rules[0]?.supported,false);});
test('vehicle exemption retained without applying to all vehicles',async()=>{const r=await parse((await xml()).replace('</condition>','<conditions xsi:type="ConditionSet"><operator>or</operator><conditions xsi:type="VehicleCondition"><negate>true</negate><com:vehicleType>heavyGoodsVehicle</com:vehicleType></conditions></conditions></condition>'));assert.equal(r.rules[0]?.supported,false);assert.ok(r.rules[0]?.vehicleConditions.length);});
test('informative source cannot authorize even in complete snapshot',async()=>{const s=await snapshot();assert.equal(engine.evaluate(query,[{...s,complete:true,rules:s.rules.map(r=>({...r,effect:'ALLOWED'}))}],now).status,'UNKNOWN');});
test('UTF8 chunk boundary preserves source description',async()=>{const s=(await xml()).replace('<regulationId>','<description><com:values><com:value>Été</com:value></com:values></description><regulationId>');const b=Buffer.from(s);const r=await parseDiaLog((async function*(){for(const byte of b)yield new Uint8Array([byte]);})(),now);assert.equal(r.rules[0]?.description,'Été');});
test('cancelled HTTP has no retry',async()=>{const c=new AbortController();c.abort();await assert.rejects(()=>new DiaLogHttpClient({fetch:async()=>new Promise(()=>{})}).download(now,c.signal),{code:'TIMEOUT'});});
test('conflicting duplicate external identity fails entire feed',async()=>{const s=await xml();const o=s.match(/<trafficRegulationOrder .*?<\/trafficRegulationOrder>/s)![0];await assert.rejects(()=>parse(s.replace(o,o+o.replaceAll('18:00:00','19:00:00'))),{code:'QUALITY'});});
